### PR TITLE
migrate the javax.annotation.* to jakarta.annotation.*

### PR DESCRIPTION
**Pull request by tmrpavan**
migrate the javax.annotation.* to jakarta.annotation.* -> https://github.com/kubernetes-client/java/issues/2606

### CODE REVIEW

**Comment by tmrpavan** [comment]
@brendanburns, @yue9944882  Can you review my PR

**Comment by tmrpavan** [comment]
@brendandburns, @yue9944882  Can you review this PR -> https://github.com/kubernetes-client/java/pull/2627

**Comment by tmrpavan** [comment]
@brendanburns, @yue9944882 Can you review my PR

**Comment by Mohdcode** [comment]
don' spam the contributor just have some patience

**Comment by brendandburns** [comment]
Unfortunately, we need to make this change in the code generator, not here, since this code is generated and these changes will get overwritten the next time we generate.

The generator repo is here:
https://github.com/kubernetes-client/gen

I think you need to add `<useJakartaEe>true</useJakartaEe>` to the `configOptions` in the `java.xml` file to activate this.

**Comment by tmrpavan** [comment]
@brendandburns 

Created PR as per your comments. Can you please review it. PR -> https://github.com/kubernetes-client/gen/pull/241

**Comment by brendandburns** [comment]
Is this PR generated by the code generator? Thanks

**Comment by tmrpavan** [comment]
@brendandburns  No, I am working on this

**Comment by tmrpavan** [comment]
@brendandburns I am getting below error while building client. Can you help me on this

--- Running generator inside container...
/usr/local/bin/mvn-entrypoint.sh: 50: exec: /generate_client.sh: not found

**Comment by tmrpavan** [comment]
I have generated the code using code generator. Still it is javax.annotation.* only. 

@brendandburns  Can you help me on this

**Comment by brendandburns** [comment]
I think that is all that the generator currently supports. Let's merge this PR for now, we can look into SSL in a follow-up.

Also, the merge bot is unhappy b/c you have an `@` symbol in your commit message. Can you remove that to make it easier to merge this PR? You can use `git commit --amend` to re-edit the commit message.

Thanks!

**Comment by tmrpavan** [comment]
@brendandburns I closed this PR and created new request https://github.com/kubernetes-client/java/pull/2642

**Pull request closed without merging**
