### PR TITLE
Rename client-java-api to *-legacy

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by brendandburns** [comment]
Sorry, I'm thinking about this some more. Do you think it would be easier to maintain this as a branch in git, rather than duplicating the code on `master`?

**Comment by yue9944882** [comment]
> Sorry, I'm thinking about this some more. Do you think it would be easier to maintain this as a branch in git, rather than duplicating the code on master?

that's definitely viable but i'm slight worried if it's as convenient to maintain as a legacy module. additionally, putting it into a separate branch will sort of double the effort for code generation for every kubernetes release because we will need to open (or automate) 2 separate PRs upon every release. do you see any downside of having a legacy module?

**Comment by yue9944882** [comment]
@brendandburns gotcha, let's move those to a separate branch then. i will file another PR after closing this!

**Comment by brendandburns** [comment]
Sounds good. Thank you!

**Pull request closed without merging**
