### PR TITLE
Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrades

### PR DESCRIPTION
**Pull request by danielburrell**
Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrades

### CODE REVIEW

**Comment by brendandburns** [comment]
fwiw, I'm ok to merge this PR, but in the future, the commits that are cherry-picked should come in as owned by the original author, not by you.

**Comment by daniel-b2c2** [comment]
@brendandburns Could you clarify? I know I posted the original release request 'issue' from my other account, but the original PR commits were done from this one and so were the cherry-picks, so the authors match I think? - unless I've misunderstood, do let me know.

**Comment by danielburrell** [comment]
@brendandburns Could you clarify please? I know the request to release came from my work account `daniel-b2c2` but the original author was this account I'm typing from, and the cherry-pick was done from the same account as far as I know. Do let me know if I've misunderstood?

**Comment by brendandburns** [comment]
oh, ok, apologies, I was confused. I think I forgot that you did the original changes, I expected the version bump to come from dependabot.

Thanks for checking (and for the PR!)

**Comment by daniel-b2c2** [comment]
Awesome, thanks for your guidance 👍  (and the release!)

**Pull request merged**
