### PR TITLE
Release 0.1

### PR DESCRIPTION
**Pull request by lwander**
Sorry for the churn, there were a few things left to fix

Non [maven-release-plugin] commits were written by me to get the release to pass.

Sonatypes validation of our artifacts has passed, I just need to update the JIRA ticket to indicate we've done our first release and the artifacts should be available after that.

### CODE REVIEW

**Comment by lwander** [comment]
Do we need to update the client capabilities badge?

**Comment by mbohlool** [comment]
So there are commits that cancel out changes from the previous commit? I see a lot of change 1.0-SNAPSHOT to 0.1-SNAPSHOT in one commit, then 0.1-SNAPSHOT to 0.1 in another commit then 0.1 to 0.2-SNAPSHOT in another one. Why is that? We probably need to create a release branch if we need those intermediate commits for the release process.

**Comment by lwander** [comment]
The release branch has already been created: https://github.com/kubernetes-client/java/tree/release-0.1 (and is pointing at the next snapshot release).

The fact that our snapshot dependencies were sitting at 1.0 was incorrect. For the maven-release-plugin to publish the artifacts at version 0.1 they need to be checked it at version 0.1-SNAPSHOT - the plugin then automatically checked in a commit at version 0.1, released that, and revved the version to 0.2-SNAPSHOT.

Further development against master is under the assumption that we will either release 0.2 or 1.0 next. Patch changes are made against the branch I linked to above.

**Comment by mbohlool** [comment]
I see, it didn't realize those two PRs were created by the maven-release-plugin. This looks good to me.

**Comment by lwander** [comment]
NP - thanks! The 0.1 release is complete :)

**Comment by mbohlool** [comment]
Nice. Thanks. Can you announce it on kubernetes dev mailing list?

**Comment by lwander** [comment]
My email should have gone out about an hour ago - kubernetes-dev @ googlegroups?

**Comment by mbohlool** [comment]
I saw it. The artifact ID is client-java-util? That is strange. I expected
client-java.

**Comment by lwander** [comment]
Let's fix that with the next release

**Comment by lwander** [comment]
https://github.com/kubernetes-client/java/issues/64

**Pull request merged**
