### PR TITLE
Update spotless version.

### PR DESCRIPTION
**Pull request by brendandburns**
Replacement for #1240 with formatting fixes added.

### CODE REVIEW

**Comment by brendandburns** [comment]
I'm really confused. #1240 seems to indicate this code change is needed (test failing) but this has tests failing too...

¯\_(ツ)_/¯

**Comment by yue9944882** [comment]
yeah, actually i attempted to fix it when i saw this.. wonder if if it's a bug in the upstream plugin..

**Comment by brendandburns** [comment]
@yue9944882 I took a deeper look at this, it looks like it is a Java8 vs java11 thing.

Java8/9/10 are failing, Java11/12/13 are passing.

What do you want to do? I suggest that we disable the formatting test for Java 8/9/10.

**Comment by yue9944882** [comment]
> @yue9944882 I took a deeper look at this, it looks like it is a Java8 vs java11 thing.
Java8/9/10 are failing, Java11/12/13 are passing.
What do you want to do? I suggest that we disable the formatting test for Java 8/9/10.

@brendandburns thanks for the clue, i updated https://github.com/kubernetes-client/java/pull/1262 to move the format verification to a separated job and it seems working now. one fun fact i confirmed is that currently the output of formatter plugin is diverging between java8 and java11 (e.g. running formatter under java8 doesnt demand any change in the ProtoExample file, while in java11 it does). i used java8 formatting in the new github action job b/c the current maven compiler plugin uses java8.. wdyt?

**Comment by brendandburns** [comment]
Fine with me, merged the fixed PR and closing this one.

**Pull request closed without merging**
