### PR TITLE
Fix the cluster initialization of the client.

### LINKED ISSUE #74: Problems w/ automatic client inside a cluster...
Reported by a user:

Hey everyone! I am having an issue running the new java-client inside a cluster. I am using
```java
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);
```
to acquire a client, which works locally, but I get this when the code is executed inside a cluster:
```java
java.lang.RuntimeException: No OAuth2 authentication configured!
```

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #74

### CODE REVIEW

**Comment by brendandburns** [comment]
@mbohlool please take a look.

Thanks!

**Comment by brendandburns** [comment]
@lwander let's get this into the 0.2 release also...

**Comment by frankreno** [comment]
@brendanburns awesome thanks!

**Comment by Frusty** [comment]
Works for me now. Thanks!

**Comment by jamescarr** [comment]
What version did this land in? `0.2`?

**Pull request merged**
