### PR TITLE
added unit tests for threads class

### PR DESCRIPTION
**Pull request by swastik959**
**added unit tests for threads class**

### CODE REVIEW

**Comment by swastik959** [comment]
@brendanburns please check this test case that I have added for threads class

**Comment by yue9944882** [comment]
please run the following command to fix the format, it looks like the new source misses a license header:

> mvn spotless:run

**Comment by swastik959** [comment]
@yue9944882 it's giving me some errors

**Comment by brendandburns** [comment]
@swastik959 you need to fix those errors, they should be straightforward, if you need help with any specific error, let us know the details.

**Comment by swastik959** [comment]
@brendandburns it's saying Could not find goal 'run' in plugin com.diffplug.spotless:spotless-maven-plugin:2.30.0 and build failure also

**Comment by brendanburns** [comment]
I think it's actually mvn spotless:apply

Thanks
________________________________

**Comment by swastik959** [comment]
@brendandburns done

**Comment by swastik959** [comment]
@brendandburns please review this pr now

**Pull request closed without merging**
