### PR TITLE
Revise the Java versions we test to LTS + latest non-LTS version.

### PR DESCRIPTION
**Pull request by brendandburns**
@yue9944882 I think we shouldn't test/support Java versions that are no longer supported by the Java team.

### CODE REVIEW

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Comment by yue9944882** [comment]
@brendandburns ah it seems that gson is not compatible w/ java 16, so the test is failing: https://github.com/google/gson/issues/1875

**Comment by brendandburns** [comment]
Yep, I'm going to see about fixing this.

**Comment by brendandburns** [comment]
@yue9944882 I figured out how to make this work by adding the command line flag: `--illegal-access=warn` to the test JVM.

This probably won't work forever, but it will at least get us working for now.

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
