### PR TITLE
Add support for easier YAML loading.

### LINKED ISSUE #170: how to load yaml file
I want to use this client to load yaml file for deployment or pod? does it support in this library? 
Thanks

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #170 

@kondapally1989 @zysimplelife @lwander 

Code now looks like:

```java
V1Pod pod = (V1Pod) Yaml.load(new File("my-file.yaml"));
```

### CODE REVIEW

**Comment by brendandburns** [comment]
Merging because of a lack of reviews...

**Comment by mmmaks** [comment]
How to load in to an specific namespace ??

**Comment by brendandburns** [comment]
You need the namespace in the Yaml file

metadata:
  namespace: Foo
...

--brendan

________________________________

**Comment by mmmaks** [comment]
`V1Pod pod = (V1Pod) Yaml.load(new File("my-file.yaml"));`
After this how can we feed this pod to kubernetes cluster ?
Using this : 
`V1Pod result = apiInstance.createNamespacedPod(namespace, body, pretty);` ??

**Comment by brendandburns** [comment]
Yes.

--brendan

________________________________

**Comment by mmmaks** [comment]
`V1Pod pod = (V1Pod) Yaml.load(new File("my-file.yaml"));`
Error : Cannot resolve method 'load(java.io.File)'

import for yaml : 
`import org.yaml.snakeyaml.Yaml;`

Any help ??

**Comment by kondapally1989** [comment]
@mmmaks 
can you paste entire error?
and did you pull latest code and generate jar

**Comment by kondapally1989** [comment]
import for YAML: 
import io.kubernetes.client.util.Yaml;

**Comment by mmmaks** [comment]
`import io.kubernetes.client.util.Yaml;`
It shows : `cannot resolve symbol 'Yaml'`

pom : 
``` 
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java</artifactId>
    <version>LATEST</version>
    <scope>compile</scope>
</dependency>```

**Comment by kondapally1989** [comment]
i think maven release doesn't contain this pull request yet 
see https://github.com/kubernetes-client/java/issues/210.
either you have to wait for new release or clone this repo and generate jar.

**Comment by mmmaks** [comment]
There is no single argument constructor in [Quantity](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java).
So when I am trying give resource limits as : 
```
resources:
   requests:
     cpu: 1
     memory: 2Gi
   limits:
     cpu: 1
     memory: 2Gi
```
It shows : 
org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for class io.kubernetes.client.custom.Quantity : null

**Comment by mmmaks** [comment]
Also, while creating Kubernetes Job, with yaml : 
    `  kind: Job`
    `apiVersion: batch/v1`
Error : 
> java.io.IOException: Unknown apiVersionKind: batch/v1/Job known kinds are:

and then a list of known kinds.
But [here](https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#job-v1-batch) shows `apiVersion: batch/v1` for job.

Also, when I try to create Job with yaml : 
`  kind: Job`
   `apiVersion: v1`

Error : 
`io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.BatchV1Api.createNamespacedJobWithHttpInfo(BatchV1Api.java:160)
	at io.kubernetes.client.apis.BatchV1Api.createNamespacedJob(BatchV1Api.java:144)`

please help !!

**Comment by kondapally1989** [comment]
@mmmaks some mappings of Kind and apiVersion  are missing.  getApiGroupVersion() doesn't contain V1Job -> batch/v1
I will try to add few mapping and create pull request.
 
 can you open issue instead of adding comments on pull request. it will be helpful/visible to others and they may quickly identify the issue

**Comment by kondapally1989** [comment]
on a 2nd look, it seems HashMap classes is never loaded with key batch/v1/Job because pojo/DTO for job is V1Job.java but not BatchV1Job.java
this will also apply to:
 Job, JobCondition, JobList, JobSpec, JobStatus

**Pull request merged**
