### PR TITLE
For Quantity class adding a no-arg constructor

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
I want to use reflection to parse the content in Yaml into the Quantity class, but I always get an error, so I want to add a parameterless constructor to this class

**demo.yaml**
```
limits:
  cpu:
    number: 0.005
    format: DECIMAL_SI
```
**DemoYaml.java**

```
package com.example.springdemo.utils;

import java.io.FileReader;

import com.esotericsoftware.yamlbeans.YamlReader;

import io.kubernetes.client.custom.Quantity;
import io.kubernetes.client.models.V1ResourceRequirements;


public class DemoYaml {
    public void transYaml() throws Exception{

        YamlReader reader = new YamlReader(new FileReader("demo.yaml"));
        V1ResourceRequirements demo = reader.read(V1ResourceRequirements.class);
        System.out.println(demo);
    }
    public static void main(String[] args) {

        Quantity x = new Quantity("5m");
        System.out.println(x);
        DemoYaml demoYaml = new DemoYaml();
        try {
            demoYaml.transYaml();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
```
**exception**

```
Caused by: java.lang.reflect.InvocationTargetException: Unable to find a no-arg constructor for class: io.kubernetes.client.custom.Quantity

```

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
> plz use `io.kubernetes.client.util.Yaml` as the decoder instead of `com.esotericsoftware.yamlbeans.YamlReader`. the former has a set of custom serializers for kubernetes specific types

This doesn't seem to solve my problem. How can I convert V1Container

**Comment by brendandburns** [comment]
You can use `Yaml.loadAs(reader, V1Container.class)`

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Yaml.java#L223

**Comment by ZP-AlwaysWin** [comment]
OK, that solves my problem perfectly。
Thanks very much @brendandburns  @yue9944882

**Comment by brendandburns** [comment]
Closing since the issue is resolved.

**Pull request closed without merging**
