### PR TITLE
[WIP] Migrating to openapi generator

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by brendandburns** [comment]
@yue9944882 

There's compile errors in this. I feel like this is what I ran into the last time I tried this, I'm not sure the custom class generator stuff works in the openapi generator. But I didn't have time to run it all the way down...

I'd really like to switch, but clearly we need the generated code to work with our custom classes.

**Comment by yue9944882** [comment]
> There's compile errors in this. I feel like this is what I ran into the last time I tried this

indeed.. i guess you're talking about [https://github.com/OpenAPITools/openapi-generator/issues/3191](https://github.com/OpenAPITools/openapi-generator/issues/3191). it'll block until an upstream fix..

**Comment by yue9944882** [comment]
/hold

until openapi v3 schema supported in k/k, it's landing in 1.16 as we planning.,

**Comment by brendandburns** [comment]
Closing this in favor of #709

**Pull request closed without merging**
