### PR TITLE
Update gson version to 2.11.0

### PR DESCRIPTION
**Pull request by ryanjbaxter**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@brendanburns seems like an issue with the build configuration?

**Comment by brendandburns** [comment]
I think you may need to backport this fix also:

https://github.com/kubernetes-client/java/commit/e931ce89a2eb82508996a0e73f5c24b7979fce67

**Comment by ryanjbaxter** [comment]
@brendandburns done, can we kick off the build again?

**Pull request merged**
