### PR TITLE
update kubernetes links & others

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubernetes-client/java/issues/2470

### CODE REVIEW

**Comment by brendandburns** [comment]
This is fine, but rather than a bunch of small PRs can we do a single big PR that fixes this for all links in any markdown file?

**Comment by Arhell** [comment]
> This is fine, but rather than a bunch of small PRs can we do a single big PR that fixes this for all links in any markdown file?

Possibly, but in the next PR

**Comment by brendandburns** [comment]
I'd prefer if you just added commits to this PR, that way it's clearer in the history. In general there's a preference for fewer PRs vs. lots of PRs.

You can add commits to your local git repo and then use `git push ..` to push them into this PR's branch.

Thanks!

**Comment by Arhell** [comment]
@brendandburns  done

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
