### PR TITLE
Switch to Java 17 for release action.

### PR DESCRIPTION
**Pull request by brendandburns**
cc @yue9944882

### CODE REVIEW

**Comment by joshlong** [comment]
hi - a propos of nothing: when's the next release planned? We'd love to have it in time for a release next week so that Spring Cloud Kubernetes can befit from these new AOT hints :)

**Comment by brendandburns** [comment]
@joshlong once this merges the release pipeline in github actions should be fixed and we will then immediately cut a release.

I would expect that we should be able to cut a release by Friday at the latest.

@wind57 this specific change doesn't benefit spring, but it unblocks our ability to cut a new release [which got broken, but we didn't notice]. In particular the new release will contain: https://github.com/kubernetes-client/java/pull/2457 which improves aot-graalvm support for this library thanks to @joshlong

**Comment by joshlong** [comment]
> @joshlong once this merges the release pipeline in github actions should be fixed and we will then immediately cut a release.
> 
> I would expect that we should be able to cut a release by Friday at the latest.
> 
> @wind57 this specific change doesn't benefit spring, but it unblocks our ability to cut a new release [which got broken, but we didn't notice]. In particular the new release will contain: #2457 which improves aot-graalvm support for this library thanks to @joshlong

thank you so very much!

**Comment by yue9944882** [comment]
oddly when i was trying to import and verify the new snapshot module `client-java-spring-aot-integration` (just in case bumping to jdk17 breaks any compatibility), the maven central snapshot repo says it doesn't exist:

```
Could not find artifact io.kubernetes:client-java-spring-aot-integration:jar:17.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```
is it because uploaded new module takes some time to be present in the central repo?

**Review by yue9944882 — COMMENTED** [review]
verified, merging in

/lgtm

**Comment by brendandburns** [comment]
@yue9944882 in my experience it takes ~24h for a package to get uploaded from sonatype to Maven central.

--brendan

**Comment by brendandburns** [comment]
@joshlong 17.0.0 release has been cut and pushed to sonatype. I would expect it in Maven Central in ~24h

**Comment by joshlong** [comment]
Congrats! And thank you

**Comment by brendandburns** [comment]
@yue9944882 @joshlong when I look at maven central, I'm not certain that I see the right files:

https://mvnrepository.com/artifact/io.kubernetes/client-java-spring-integration

Only shows 16.0.2

Can you take a look and see? I'm worried that we may need to do some more modifications to either the pom or the github action.

(or am I not looking in the right place?)

**Comment by joshlong** [comment]
so _some_ of the modules are being deployed but others are? i see the `client-java-spring-aot-integration` in the `modules` stanza in the parent. i just did a `mvn -DskipTests install` and I see the spring aot integration deployed to my local  `~/.m2/repository`.  so that's a start. guess I need to try to understand the deployment pipeline a bit more, cuz nothing's leaping out to me here in the pom.xm files.

**Comment by joshlong** [comment]
à propos: is there any output from during the release that gives a clue as to what may have happened?

**Comment by joshlong** [comment]
hah. i think we got had by a cache issue. different index on a different site shows this :) 

https://search.maven.org/artifact/io.kubernetes/client-java-spring-aot-integration/17.0.0/bundle

**Comment by brendandburns** [comment]
@joshlong great to get the confirmation that it is working and indeed I see them in maven central now. Must have just been replication lag.

**Pull request merged**
