### PR TITLE
Release 11.0.0

### LINKED ISSUE #1441: Cutting 11.0.x releases
@brendandburns as a new release of k/k is out last month, let's cut a new major release wdyt?

### PR DESCRIPTION
**Pull request by brendandburns**
This is staged to Sonatype and should be in Maven Central in ~24 hours.

I had to hack around with the examples pom.xml files a little to get the release to build. We'll need to automate that some more for future versions...

Fixes #1441

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@brendanburns I still do not see this in maven central yet

**Comment by brendandburns** [comment]
@ryanjbaxter it definitely got pushed. There's always a bunch of lag getting into Maven Central.

If it's not there by ~Monday, I will investigate.

**Comment by ryanjbaxter** [comment]
@brendanburns I see 9.0.3 was published on the 18th, was that something separate?

**Comment by brendandburns** [comment]
@ryanjbaxter I don't know what is going on. I pushed both releases (`11.0.0` and `9.0.3`) at the same time. I'm not sure what's going on. I'll try to investigate.

**Comment by yue9944882** [comment]
i didnt see 11.0.0 release either 🤔

**Comment by brendandburns** [comment]
Closing this in favor of #1453 

This is now actually staged to sonatype...

**Comment by brendandburns** [comment]
I see this in https://oss.sonatype.org (https://oss.sonatype.org/service/local/repositories/releases/content/io/kubernetes/client-java/11.0.0/client-java-11.0.0.jar)

So I now believe that it will be in maven central in ~24hrs.

**Pull request closed without merging**
