### PR TITLE
Cherry Pick For 17.x - Compensating changes for SnakeYAML 2.0

### PR DESCRIPTION
**Pull request by ryanjbaxter**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Thanks @brendandburns!  Any idea when the next 17.x release will happen?

**Comment by ryanjbaxter** [comment]
@brendandburns just a reminder

**Comment by brendandburns** [comment]
Apologies I didn't see this. Will try to cut a new release soon-ish (by end of next week at the latest)

**Comment by brendandburns** [comment]
ok, the release action just completed successfully:
https://github.com/kubernetes-client/java/actions/runs/4695262263

I would expect that `17.0.3` shows up in maven central in ~24hrs.

**Comment by ryanjbaxter** [comment]
Thanks!  And I think you mean `17.0.2`

**Pull request merged**
