### PR TITLE
Project to control its own maven version.

### PR DESCRIPTION
**Pull request by westse**
- See https://github.com/takari/maven-wrapper

I have found this useful to both control the maven version, as well as to remove the requirement that maven is even pre-installed on the developer's machine (./mvnw downloads it for you if necessary).

Does this practice fit well here too?

### CODE REVIEW

**Comment by brendandburns** [comment]
@lwander is our Maven packaging expert... I defer to him.

**Comment by lwander** [comment]
:sweat: not an expert at all... 

@westse is this similar to gradle's `gradlew` wrapper script? It seems useful

**Comment by westse** [comment]
@lwander , yes in fact it was copied from `gradlew` wrapper because they though it was a good idea for more reproducible builds and developer convenience.

**Comment by lwander** [comment]
Sweet, this seems great. Is there any way to avoid checking in maven-wrapper.jar? Should the script be fetching that?

**Comment by westse** [comment]
At this point the jar is expected to be checked in (gradlew does this as well). That said, it looks like they are working on support for not having the Jar checked in: https://github.com/takari/maven-wrapper/pull/70

**Comment by lwander** [comment]
Cool, works for me

**Pull request merged**
