### PR TITLE
Simplify usage of Bucket4j via using new API method consumeIgnoringRateLimits which was added in the version 4.8.0

### PR DESCRIPTION
**Pull request by vladimir-bukhtoyarov**
Hello guys,

As the author of Bucket4j, I had done review the usage of my library in the kubernatess-client/java and me found that code can be reduced a lot if upgrade from ```4.4.1``` to ```4.8.0```.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR!

This looks good to me, but it needs some formatting fixes. Can you run:

`mvn fmt:format`

Also, we need you to sign the CLA.

**Comment by vladimir-bukhtoyarov** [comment]
I will do

**Comment by brendandburns** [comment]
This looks good to me. @yue9944882 any concerns?

**Comment by brendandburns** [comment]
/approve
/lgtm

Thanks for the PR

**Pull request merged**
