### PR TITLE
Update to 1.12 generated code. Fix a few compile errors w/ the new code.

### PR DESCRIPTION
**Pull request by brendandburns**
@cliveseldon

### CODE REVIEW

**Comment by brendandburns** [comment]
@cliveseldon any chance you can review this?

Thanks!

**Comment by cliveseldon** [comment]
Builds and installs from fresh checkout ok. Will looks at the examples.

**Comment by cliveseldon** [comment]
I have tested the examples that are standalone and they work. So looks ok to me.

**Comment by brendandburns** [comment]
@cliveseldon I sent you an invite to be a member of this repository so that I can assign issues to you so that you can /lgtm :)  *sigh* sorry the process is so long.

I'll self lgtm for now.

**Comment by brendandburns** [comment]
@slonka sadly no, that requres the Kubernetes project to migrate to OpenAPI 3.0 which hasn't happened yet.

**Pull request merged**
