### PR TITLE
make background threads in LeaderElector to be daemon

### PR DESCRIPTION
**Pull request by himanshug**
or else java application doesn't successfully exit  on finishing main() method.

~~TODO:  Figuring out CLA signing  details shortly.~~

### CODE REVIEW

**Comment by himanshug** [comment]
will fix the build after CLA is done.

**Comment by brendandburns** [comment]
Thanks for the PR, this looks good to me, but the CLA bot is confused. Do you have your email attached to your github account?

**Comment by himanshug** [comment]
@brendanburns thanks for taking a look, yeah I am trying to resolve the cla issue.. currently state is that
- commits have my personal gmail id in them as author
- github account has multiple emails on profile including my work email id (@splunk.com) and my personal gmail id
- linuxfoundation account ( https://identity.linuxfoundation.org/user/me ) does show me in the group "CNCF - Splunk", has  my work email on file(since it allows only one email id), "Github" Auth Provider with Identity "https://github.com/himanshug"  on "Social network logins" tab.

I "thought" cla bot would determine that my github account is "himanshug" which is attached to linuxfoundation account "himanshug"  which is in the group "CNCF - Splunk" and everything checks out.
I am trying to figure out what is missing, one obvious thing is to use my work email as commit author but I am trying to see if that is really necessary as dots can be connected because my work and personal, both email ids are in github profile.

**Comment by himanshug** [comment]
created a cla support issue , will update here once that is resolved.

**Comment by himanshug** [comment]
Got this from support team (just in case someone else gets issues due to same problem and internet search leads them here) ...
```
You are in the correct group to be authorized - CNCF-Splunk. The thing missing is that whoever added you didn't specify your role - either if you were a contributing employee or a manager. The CLA manager needs to add the contributing employee role to you before you can pass a CLA check. Id suggest they review all of the users in the Splunk group as there are many with no role defined.

Your CLA manager will log into identity.linuxfoundation.org --> click CNCF-Splunk in their profile -->"Manage Group" tab -->People --> and then they can edit the individual users. "Contributing Employee" has to be checked under "Roles" for anyone to pass the CLA check. 
```

will update if that fixes the cla issue.

**Comment by himanshug** [comment]
@brendanburns cla check is done.

**Pull request merged**
