### PR TITLE
Fixed field names for explicit substitution

### PR DESCRIPTION
**Pull request by telyatnikov**
For substitution we have to use field names, for example `xKubernetesEmbeddedResource` instead of `x-kubernetes-embedded-resource`.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thank you for the PR! Can you add a unit test that demonstrates the broken behavior and validates that this PR fixes it (and so that it stays fixed in the future)

**Comment by telyatnikov** [comment]
I've included a unit test that demonstrates the absence of the added property in TypeDescription.

**Comment by brendandburns** [comment]
Cool thank you! fwiw, I didn't mean that you had to revert your fix and prove to me that it would fail, but I appreciate that you did!

You can add the fix back in and we can get this merged.

Thank you!

**Comment by telyatnikov** [comment]
I had to figure out why the tests failed after my 'fix' and how PropertySubstitute from snakeyaml actually works. Well, my fix proved to be incorrect. 

But maybe my attempt will be useful in some way - I've found that one of the extensions - `x-kubernetes-validations` wasn't included. I added the relevant unit test and fix. I aimed to make the search for required substitutions more flexible and get rid of hardcoded annotations. 

I'm really sorry for wasting your time and jumping into things without testing or thinking it through. Thanks for your understanding!

**Pull request closed without merging**
