### PR TITLE
Use synchronization classes instead of Thread.sleep in test cases

### PR DESCRIPTION
**Pull request by tmrpavan**
Use synchronization classes instead of Thread.sleep in test cases

[Umbrella Issue] Many tests use Thread.sleep instead of synchronization primitives https://github.com/kubernetes-client/java/issues/1223

### CODE REVIEW

**Comment by tmrpavan** [comment]
@brendandburns  Can you review my PR

**Comment by brendandburns** [comment]
In this context, I'm not sure that sleep is a problem. We need to wait for a period of time, but we expect to be interrupted. Adding the `lock.wait(10s)` instead of `sleep(10s)` doesn't really change the expectation of an interrupt and I don't think it makes this test less flaky.

You could, in theory, make this test less flaky by blocking the thread until just before shutdown is called, and _then_ waiting for a period of time to get interrupted by shutdown, but I don't think it's worth it.

**Comment by brendandburns** [comment]
(oh and many thanks for taking on these type of PRs, they're generally useful and hard to get contributions, so thanks! it's just that this one may not be quite as useful as others)

**Comment by tmrpavan** [comment]
@brendandburns Thanks for your comments. I will work on this

**Comment by tmrpavan** [comment]
@brendandburns Can you please review this PR

**Comment by brendandburns** [comment]
I don't think that this change is really any different than the code that is already there. I think in this case, Thread.sleep(...) is actually the right thing to do in this test.

Let me know if I'm missing something.

Thanks!

**Pull request closed without merging**
