### PR TITLE
Handler for notifying that Reconcile for Object that existed before DefaultController is started is completed

### PR DESCRIPTION
**Pull request by deftfitf**
https://github.com/kubernetes-client/java/issues/2699

### CODE REVIEW

**Comment by yue9944882** [comment]
close and reopen to trigger tests

**Comment by deftfitf** [comment]
https://github.com/kubernetes-client/java/actions/runs/5980599431/job/16227046834
The Maven tests failed, even though they passed on my local environment using JDK `temurin-17.0.8`...

```
...
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
[INFO] Running io.kubernetes.client.extended.controller.DefaultControllerTest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.318 s -- in io.kubernetes.client.extended.controller.DefaultControllerTest
...
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.808 s -- in io.kubernetes.client.extended.pager.PagerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 103, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.10:report (jacoco-report) @ client-java-extended ---
[INFO] Loading execution data file ...
[INFO] Analyzed bundle 'client-java-extended' with 82 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by yue9944882** [comment]
@deftfitf this is weird, not seeing any test jobs in this PR. do you mind open a new one so that we can run the tests?

**Comment by deftfitf** [comment]
@yue9944882 sure. I'll create the new one.

**Comment by deftfitf** [comment]
Here's new one. Could you check this?
https://github.com/kubernetes-client/java/pull/2803

**Pull request closed without merging**
