### PR TITLE
fix for NO_EXECUTE toString Method

### LINKED ISSUE #2340: `Taints.Effect.NO_EXECUTE.toString()` returns "NoExcute" instead of "NoExecute"
**Describe the bug**

the enum value `Taints.Effect.NO_EXECUTE`'s toString() method returns "NoExcute" instead of "NoExecute".

source code: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/taints/Taints.java#L35

**Client Version**
`16.0.0`

**Kubernetes Version**
`1.24.3`

**Java Version**
`Java 8`

**To Reproduce**
add a taint to a node with:
```java
import io.kubernetes.client.extended.kubectl.Kubectl;
import io.kubernetes.client.extended.kubectl.exception.KubectlException;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.util.Config;

import java.io.IOException;

class Main{
    public static void main(String[] args) throws KubectlException, IOException {
        Configuration.setDefaultApiClient(Config.defaultClient());
        String nodeName = "myk8s-4nodes-worker";
        // neither "NoExecute" or "NoExcute" will work
        Kubectl.taint().name(nodeName).addTaint("key", "value", "NoExecute").execute();
    }
}
```

**Expected behavior**
taint (with Effect "NoExecute") should be added correctly

### PR DESCRIPTION
**Pull request by priyal13m**
- fixed spelling mistake in NO_EXECUTE toString Method.
- added unit tests for NO_EXECUTE toString Method

Fixes #2340

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for the PR!

**Comment by priyal13m** [comment]
@brendandburns - This is my first PR and need some guidance here. Java 11.0.x Maven Test on windows-latest failed for - 

> Error:  testSimpleRateLimitQueue(io.kubernetes.client.extended.workqueue.DefaultRateLimitQueueTest)  Time elapsed: 0.518 s  <<< FAILURE!

**Pull request merged**
