### PR TITLE
#1802 Check if server is available from kubeconfig.

### PR DESCRIPTION
**Pull request by cbuschka**
Added null check with IllegalArgException and added a test case to ClientBuilderTest.

### CODE REVIEW

**Comment by brendandburns** [comment]
Looks good, but you need to run `mvn spotless:apply` to format the code.

**Comment by brendandburns** [comment]
@cbuschka apologies but we're apparently in the middle of transitioning CLA bots, you'll need to sign the older CLA for now. Sorry for the noise.

**Comment by cbuschka** [comment]
@brendandburns No worries, I have signed two CLAs. One with DocuSign and one with HelloSign. Can you point me to a place I can recheck if something is still missing?

**Comment by brendandburns** [comment]
Thanks for the patience. merging.

**Pull request merged**
