### PR TITLE
Exlude com.sun.tools from io.sundr.builder-annotations transitive dep…

### PR DESCRIPTION
**Pull request by mtsr**
…endencies

Solves https://github.com/kubernetes-client/java/issues/333

### CODE REVIEW

**Comment by mtsr** [comment]
Signed CLA for corporate email address...

**Comment by mtsr** [comment]
Signed CLA for corporate email address...
/check-cla

**Comment by mtsr** [comment]
Hmm, again
/check-cla

**Comment by jglick** [comment]
This does not suffice. In a project using this library I cannot build on Windows:

```
[ERROR] 'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is /usr/lib/jvm/java-8-jdk/jre/../lib/tools.jar @ io.sundr:sundr-codegen:[unknown-version], c:\…workspace…\.repository\io\sundr\sundr-codegen\0.9.2\sundr-codegen-0.9.2.pom, line 54, column 19
```

(https://github.com/jenkinsci/google-kubernetes-engine-plugin/pull/4#issuecomment-461818176 was a similar case I encountered a while back.)

Picking up https://github.com/sundrio/sundrio/pull/118 does not help. The problem is not that `com.sun:tools` is in the dependency tree but that the POM itself is considered invalid.

Workaround is to

```xml
<exclusion>
    <groupId>io.sundr</groupId>
    <artifactId>sundr-codegen</artifactId>
</exclusion>
```

when using this lib.

**Pull request merged**
