### PR TITLE
update maven wrapper

### PR DESCRIPTION
**Pull request by isopov**
Maven wrapper used seems to be a bit old. This PR updates it.

### CODE REVIEW

**Comment by brendandburns** [comment]
@isopov thank you for the PR. Can you document the process that you used for for updating this? I want to make sure that we can do it again in the future.

Thanks
--brendan

**Comment by isopov** [comment]
@brendanburns This is the result of command `./mvnw -N io.takari:maven:0.7.7:wrapper` (took this from https://github.com/takari/maven-wrapper and checked against https://search.maven.org/ that it is the latest version of this update tool)

**Comment by yue9944882** [comment]
@isopov thank, it seems that this pull is constantly failing due to certificate error. am still working on unwinding it...

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

thanks!

**Pull request merged**
