### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Sajal-12**
This Updated file includes with Kubernetes official tutorial documentry link along with some updated basic concepts. Hope you will include this on your Readme file . pls accept this update and improve it to better.

### CODE REVIEW

**Comment by Sajal-12** [comment]
Hope you will add this and give a sign to me so I learn more about it and work on this for future times. I'm excited to work with you guys please add this so I get motivated to work with you guys for further time span.

**Comment by brendandburns** [comment]
@yue9944882 wdyt? I'm not sure if we want extensive Kubernetes documentation in the client, I feel like people should know about Kubernetes before they find this client library.

**Comment by Sajal-12** [comment]
assign @brendandburns

**Comment by yue9944882** [comment]
> @yue9944882 wdyt? I'm not sure if we want extensive Kubernetes documentation in the client, I feel like people should know about Kubernetes before they find this client library.

@brendandburns aesthetically i'm leaning on keeping a short/neat README and expand more details in the wiki page. as for the purposed changes in this PR, i think these docs about kubernetes basics are valid in a sense, i will copy/move them to wiki page in the future. thanks for your contribution @Sajal-12 i will hold this pull until they're moved to wiki

/hold

**Comment by Sajal-12** [comment]
@yue9944882 yeah np , Thanks to hear from you

**Pull request closed without merging**
