### PR TITLE
Regenerate for 1.30, fix patches

### PR DESCRIPTION
**Pull request by brendandburns**
@yue9944882 I regenerated for 1.30 including the fixes for nullable arrays, also fixed up the patches so they applied cleanly.

Ref https://github.com/kubernetes-client/java/issues/3076

~Please take a look.~

~Tests are failing b/c the YAML is being generated with empty lists intead of nulls, I'm not sure this is easily fixable but will investigate.~

~YAML is fixed, but one JSON test is failing and needs a fix.~

This is ready for review.

### CODE REVIEW

**Comment by brendandburns** [comment]
Ok, I updated this so that empty lists are omitted from YAML dumping and I _think_ that should be ok.

**Comment by yue9944882** [comment]
```
Error:    KubectlDeleteTest.kubectlDelete:216 No requests exactly matched. Most similar request was:  expected:<
DELETE
/apis/batch%2Fv1/batch%2Fv1/namespaces/foo/jobs/bar

[equalToJson]
{
  "propagationPolicy" : "Foreground"
}> but was:<
DELETE
/apis/batch%2Fv1/batch%2Fv1/namespaces/foo/jobs/bar


{
  "dryRun" : [ ],
  "propagationPolicy" : "Foreground"
}>
```

it looks like k/k api added a new dry-run option for delete API, so we need to align with that. i will append another commit to fix it

**Comment by brendandburns** [comment]
@yue9944882 this is fixed up and ready to review, I tried to keep the commits separate for easier reviewing, but I'll likely squash them in the end to fix the issues with authorship and the PR bot.

I had to remove a check from `KubectlDrain.java` to get tests to pass, but I'm not sure that it really made sense in the first place anyway. Also added an `exclusion strategy` to GSON for `metadata.managedFields`

**Comment by yue9944882** [comment]
> EasyCLA — Missing CLA Authorization.

This PR failed CLA check due to bot commit, let me squash the branch into single commit to workaround

**Comment by brendandburns** [comment]
manual lgtm, since I'm the original author of the PR.

**Pull request merged**
