### PR TITLE
Add logging dependency to e2e tests.

### PR DESCRIPTION
**Pull request by brendandburns**
Improves logging for e2e tests.

Ref #1480

### CODE REVIEW

**Comment by yue9944882** [comment]
@brendandburns do we still want this? it's intended for easing flakiness which is already solved i suppose?

**Comment by brendandburns** [comment]
@yue9944882 I think we do still want this. Without it the real cluster integration tests don't have any logs and so failures are really hard to debug. So I think it is worth leaving this in for future debugging of flakes or other failures.

While with unit tests it's fairly easy to debug w/o logs, the real cluster integration tests are much harder to debug that way without all of the logging that the various components do in a real system.

**Comment by brendandburns** [comment]
@yue9944882 friendly ping on this PR.

Thanks!

**Comment by brendandburns** [comment]
e2e flaked again:
https://github.com/kubernetes-client/java/pull/1574

Having these logs would make it feasible to debug such failures.

**Comment by brendandburns** [comment]
@yue9944882 friendly ping on this one.

**Comment by brendandburns** [comment]
@yue9944882 can I get an LGTM on this one?

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Pull request merged**
