### PR TITLE
fix: correct work of DaemonSetIgnore

### PR DESCRIPTION
**Pull request by Duranna66**

### CODE REVIEW

**Comment by brendandburns** [comment]
@Duranna66 which of these two PRs should I review?

**Comment by Duranna66** [comment]
@brendandburns last pr, where 3 days ago

**Comment by brendandburns** [comment]
/lgtm

This looks good to me, but we need you to sign the CLA.

Thanks!

**Comment by Duranna66** [comment]
Hope I will do that on this weekends

**Comment by callingmahendra** [comment]
If CLA is an issue, I can also raise PR with the same changes. Let me know.

**Comment by Duranna66** [comment]
> If CLA is an issue, I can also raise PR with the same changes. Let me know.

I will try one more time

**Comment by Duranna66** [comment]
> If CLA is an issue, I can also raise PR with the same changes. Let me know.

okey, i don't have time for changing my email and reopen pr(  You can raise PR with the same changes

**Comment by dasarathirout** [comment]
> /lgtm
> 
> This looks good to me, but we need you to sign the CLA.
> 
> Thanks!

Made PR https://github.com/kubernetes-client/java/pull/3582 with the same changes ,its passed CLA check

**Comment by brendandburns** [comment]
closing in favor of #3582

**Pull request closed without merging**
