### PR TITLE
Backport changes for GenericKubernetesApi, PartialObjectMetadata, and SnakeYAML 2.0

### PR DESCRIPTION
**Pull request by rjeberhard**

### CODE REVIEW

**Comment by brendandburns** [comment]
Did this not work as a cherry-pick? In general, I'd prefer a cherry-pick PR instead of a new PR.

Thanks!

**Comment by rjeberhard** [comment]
> Did this not work as a cherry-pick? In general, I'd prefer a cherry-pick PR instead of a new PR.

It may be just me, but I can't seem to get cherry-picks to work in the forked repo.

**Comment by rjeberhard** [comment]
I don't absolutely need this backported if you do end up releasing an 18.0.0.

**Comment by brendandburns** [comment]
Cherry-picks should work assuming that you have an upstream setup in your fork:

Here's what I do:

`git add remote upstream https://github.com/kubernetes-client/java`
`git fetch upstream`
`git cherry-pick <some-commit-hash>`


I'm in the midst of running the `18.0.0` release though.

**Comment by rjeberhard** [comment]
I'll close this for now and will try your suggestion should we need to request a 17.0.2 or for future backports.

**Comment by ryanjbaxter** [comment]
@brendandburns I would be in favor of backporting this to 17.x and 13.x if possible.  We have to branches that we are still maintaining based on these releases.  I realize the 13.x backport would be a big ask though...

**Pull request closed without merging**
