### PR TITLE
Add support for terminal resize in ExecProcess

### PR DESCRIPTION
**Pull request by brendandburns**
Reimplements #3657 since that PR has gone idle.

### CODE REVIEW

**Comment by brendandburns** [comment]
There's something wrong with the tests.

**Comment by brendandburns** [comment]
Ok, this should now be ready for review.

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Comment by brendandburns** [comment]
self-lgtm, since the changes were just to address a rebase conflict.

**Pull request merged**
