### PR TITLE
Graceful shutdown sharedprocessor

### LINKED ISSUE #1134: Shutdown of SharedProcessor
I believe the shutdown of the shared processor is designed to be graceful. It will wait one minute for each informer. This means that for each informer it will wait one minute. These waits are not done in parallel but in sequence. This means that if you have say 10 informers it will wait 10 minutes. It doesn't seem correct? Furthermore, it would be nice if there was a way to say "don't wait, just shutdown now" for testing.

### PR DESCRIPTION
**Pull request by yue9944882**
Fixes #1134

### CODE REVIEW

**Comment by dddddai** [comment]
The following test should be removed, because `stop()` would interrupt running listeners immediately

https://github.com/kubernetes-client/java/blob/master/util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java#L70-L83

**Comment by yue9944882** [comment]
> The following test should be removed, because stop() would interrupt running listeners immediately

thanks for reminding, removed the related tests

**Comment by tony-clarke-amdocs** [comment]
Which branch will this fix make its way into?

**Comment by yue9944882** [comment]
> Which branch will this fix make its way into?

it's targeting master

**Comment by tony-clarke-amdocs** [comment]
> > Which branch will this fix make its way into?
> 
> it's targeting master

Will there be a 9.0.1 release with this? If not, what would be the next release that would include this change? Thanks.

**Comment by yue9944882** [comment]
> Will there be a 9.0.1 release with this?

@tony-clarke-amdocs we can get this fix into master then cherry-pick to release branches then publish a 9.0.1 @brendandburns wdyt?

**Comment by brendandburns** [comment]
/lgtm
/approve

Yes, I'm happy to cut a `9.0.1` release.

**Comment by tony-clarke-amdocs** [comment]
Thanks, will pick this up from 9.0.1

**Comment by brendandburns** [comment]
@yue9944882 as long as we're cherry-picking, I want to get #1145 merged and pick that too.

**Comment by tony-clarke-amdocs** [comment]
@brendanburns I don't see this in the 9.0.1 release?

**Comment by brendandburns** [comment]
@tony-clarke-amdocs I see it here in the branch:

https://github.com/kubernetes-client/java/commits/release-9.0.0

Do you mean that the fix isn't in the Maven package? What symptoms are you seeing?

I believe that everything should be there, but it's possible that something went wrong.

**Comment by brendandburns** [comment]
@tony-clarke-amdocs 

Also, if there is a problem that you are seeing, can you file a new issue, it's tricky to track discussions on pull requests that have been closed, it will be easier if there is an open issue.

Thanks!

**Pull request merged**
