### PR TITLE
Removing static port in Junit tests

### PR DESCRIPTION
**Pull request by sarveshkaushal**
Related to #1229

### CODE REVIEW

**Comment by sarveshkaushal** [comment]
I tried running tests for both Java 8 and Java 11. It ran successfully for me.
java version "1.8.0_241
openjdk version "11.0.6" 2020-01-14

**Comment by yue9944882** [comment]
can you rebase onto the latest master? #1228 fixed the flakiness

**Comment by sarveshkaushal** [comment]
> #1228

This is already rebased into master.

**Comment by sarveshkaushal** [comment]
Is it possible to re-trigger the build?

**Comment by yue9944882** [comment]
@sarveshkaushal can you rebase this pull onto https://github.com/kubernetes-client/java/pull/1239? i hope that will completely fix the flakiness..

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Pull request merged**
