### PR TITLE
Add source jars to deployment

### LINKED ISSUE #1406: Source jars not generated for snapshots locally
I can see there is some confusion about source jars (#598 #597), but there are no source jars available locally when I build this project from source. I am confused because I see source jars in Maven Central (for releases), but no sign of how they got there. I also don't know if there is a snapshot repository (I see no sign of it in the poms) where I can get them if I don't want to build locally. Can we add the source plugin to the build, maybe?

### PR DESCRIPTION
**Pull request by dsyer**
Fixes #1406

### CODE REVIEW

**Comment by dsyer** [comment]
/assign @brendandburns

I'm having issues getting the bot to recognise the CLA. I'll see if there's anything I can do this end.

**Comment by dsyer** [comment]
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

I don't event know what that means. Maybe I'll just push the code again? Help?

**Comment by brendandburns** [comment]
The commit stuff seems to have sorted itself out, but how is this different than the previous mention of the same plugin:
https://github.com/kubernetes-client/java/blob/master/pom.xml#L345

I'll freely admit to not being an expert in pom files.

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Comment by dsyer** [comment]
>  how is this different than the previous mention of the same plugin

In 2 ways: 1. the previous mention is in the `<pluginManagement/>` section so it only governs the default settings when a plugin is actually invoked, 2. it doesn't declare any goals, so it wouldn't do anything (probably).

**Pull request merged**
