### PR TITLE
Cherry Pick #2952 To Release 19

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Cherry pick #2952 to Release-19 branch

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@brendanburns @yue9944882 this is another one for the Release-19 branch

**Comment by brendandburns** [comment]
@ryanjbaxter thanks for the PR, but there are 5 commits in the original PR after the review, can you cherry-pick all of those commits?

In particular, I want the change that requires that the `jar:` URL prefix is there so that we don't load JARs across the network.

**Comment by ryanjbaxter** [comment]
@brendandburns Sure the additional commits should be there now

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for the quick turn around.

**Comment by yue9944882** [comment]
>https://github.com/kubernetes-client/java/pull/3813

looks like we need to rebase this PR after the above one get merged

**Comment by ryanjbaxter** [comment]
@yue9944882 yes!  Will do after it is merged!

**Comment by ryanjbaxter** [comment]
@brendandburns @yue9944882 I have rebased this PR can we run the build again?

**Comment by brendandburns** [comment]
@ryanjbaxter I pushed a `19.0.2` release up to sonatype, should be in maven central in ~24hr

https://repo1.maven.org/maven2/io/kubernetes/client-java/19.0.2/

**Comment by ryanjbaxter** [comment]
Excellent thank you!

**Pull request merged**
