### PR TITLE
Cherry Pick #1963 To 13.0

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Would like #1963 in the 13.0 branch as well

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@yue9944882 sorry for yet another PR here, but we need this in the 13.0 branch as well for the spring cloud kubernetes 2.1.x branch.  We would need a 13.0 release as well after it is merged

**Comment by brendandburns** [comment]
/lgtm
/approve

I will try the release workflow.

**Comment by ryanjbaxter** [comment]
@rendandburns thanks! do you want me to create an issue for the release?

**Comment by brendandburns** [comment]
No need, 13.0.2 was just pushed out to sonatype, should be in maven central in ~24hours.

**Comment by ryanjbaxter** [comment]
Thanks I will check tomorrow!

**Comment by ryanjbaxter** [comment]
All good thanks!

**Pull request merged**
