### PR TITLE
Fix the metadata.annotations too long issue

### PR DESCRIPTION
**Pull request by hippoz**
Proposed fix to issue https://github.com/kubernetes-client/java/issues/2619

### CODE REVIEW

**Comment by brendandburns** [comment]
Looks good to me, but I wanted @yue9944882 to have a chance to look since it's his script.

**Comment by lobocode** [comment]
> Looks good to me, but I wanted @yue9944882 to have a chance to look since it's his script.

@hippoz  I found the proposed script very interesting as it tackles the issue of failing Java Model Generation due to long CRD annotations by installing the CRD definitions in a KinD cluster to ensure their validity, using Swagger spec to generate the Java model classes instead of the crd-model-gen tool which struggles with long annotations, verifying that the CRD installation and Swagger publishing were successful, and copying the generated model classes to the output directory.

**Comment by hippoz** [comment]
> > Looks good to me, but I wanted @yue9944882 to have a chance to look since it's his script.
> 
> @hippoz I found the proposed script very interesting as it tackles the issue of failing Java Model Generation due to long CRD annotations by installing the CRD definitions in a KinD cluster to ensure their validity, using Swagger spec to generate the Java model classes instead of the crd-model-gen tool which struggles with long annotations, verifying that the CRD installation and Swagger publishing were successful, and copying the generated model classes to the output directory.
> 
> I suggest you sign the https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677673/90675730/2621/#/?version=2 Easy CLA CNCF model 👍

Hi @lobocode , good day! Thanks! Actually, I have already signed the CLA and received the confirmation email. However, it still prompts me to sign it again. Is there anything else I need to do to proceed?

**Comment by yue9944882** [comment]
LGTM, can you sign the CLA so the pull can proceed? @hippoz

**Comment by brendandburns** [comment]
@hippoz friendly check in on the CLA, otherwise I will need to close this PR to keep the repo clean.

**Comment by liangyuanpeng** [comment]
Resolved by https://github.com/kubernetes-client/java/pull/2670

**Pull request closed without merging**
