### PR TITLE
gh-1398 swapped javadoc on filters

### PR DESCRIPTION
**Pull request by d47853**

### CODE REVIEW

**Comment by d47853** [comment]
I have now signed the cla

**Comment by yue9944882** [comment]
> From 7b8053c7dfeb1ee388311443bde26de02b7e447d Mon Sep 17 00:00:00 2001
> From: d47853 <d47853@users.noreply.github.com>

ur commit is signed by an invalid email address, plz use the same email as the one you signed the CLA

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Comment by yue9944882** [comment]
@d47853 thanks for fixing this!

**Comment by d47853** [comment]
I use a github.noreply email in my git commits which I couldn't use in the CLA. I just used the standard github integration for the CLA

**Comment by yue9944882** [comment]
> I use a github.noreply email in my git commits which I couldn't use in the CLA. I just used the standard github integration for the CLA

amending the commit using the email signed CLA will work

**Comment by d47853** [comment]
I've updated the email and re-signed the CLA

**Comment by brendandburns** [comment]
@yue9944882 I think this was fixed in a different PR, right?

**Pull request closed without merging**
