### PR TITLE
Updated expanded example comment

### PR DESCRIPTION
**Pull request by mans2singh**
Updated comment from <code>List all of the **namaspaces** and pods</code> to <code>List all of the **namespaces** and pods</code>

### CODE REVIEW

**Comment by brendandburns** [comment]
@mans2singh if you push a new commit it will retrigger the tests. 
 
Some of the tests are flaky (sorry!) so they fail unrelated to changes every once in a while.

**Comment by mans2singh** [comment]
Thanks @brendandburns - Do you have any advice/recommendations of improvements for this minor PR or should I just push a simple commit just to trigger the build ?

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Comment by mans2singh** [comment]
Thanks @brendandburns @yue9944882 for your time.

**Pull request merged**
