### PR TITLE
Update generate.yml to use Java 11

### PR DESCRIPTION
**Pull request by brendandburns**
Needed for spotless formatting to work correctly.

cc @yue9944882

### CODE REVIEW

**Comment by brendandburns** [comment]
@yue9944882 the one test failure is fixed in #2688

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Comment by yue9944882** [comment]
@brendandburns the CRD generator fix is merged, let's rebase on top of that

**Comment by brendandburns** [comment]
@yue9944882 rebased.

**Comment by brendandburns** [comment]
This PR got messed up by rebasing. I'm going to close and create another.

**Pull request closed without merging**
