### PR TITLE
Propose release 1.0.0-beta3

### PR DESCRIPTION
**Pull request by brendandburns**
@lwander @lewisheadden @rjeberhard

### CODE REVIEW

**Comment by rjeberhard** [comment]
If possible, and if #213 is approved, I'd be grateful if you could hold declaring beta3 until that PR is included.

**Comment by rjeberhard** [comment]
Can we please get this moving?  Thanks.

**Comment by rjeberhard** [comment]
@brendandburns I'm waiting with baited breath for this release so we can tag the next version of our project.  I've also verified that we can still pass all of our tests with your regenerated client PR.  Any estimate on when this will go in?  Thanks.

**Comment by brendandburns** [comment]
I'm going to try to build/push this today.

I wanted to get in the existing open PRs and was waiting on review.

But if it doesn't show up I'll just merge and release...

--brendan

________________________________

**Pull request merged**
