### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by brendandburns**
@cliveseldon @kondapally1989

### CODE REVIEW

**Comment by cliveseldon** [comment]
Your changes refer to 5.0.0 in the poms but the title of this PR is 4.0.0. Maybe I am missing something obvious of how you are doing releases?

**Comment by brendandburns** [comment]
@cliveseldon this contains the tag for the 4.0.0 release, and then a move to the new 5.0.0-SNAPSHOT branch... See this commit:

https://github.com/kubernetes-client/java/pull/505/commits/1fcf70c44c5b3ad535945cecc6c069f00f1e5379

Sorry, this is how the `mvn release` command does things, I agree it's a little confusing...

**Comment by hobdell-SAP** [comment]
CHANGELOG.md seems to be missing the changes for 4.0.0 - is this intentional?

**Pull request merged**
