### PR TITLE
Update protocol buffers and protocol buffer dependency.

### PR DESCRIPTION
**Pull request by brendandburns**
cc @codefromthecrypt

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
I'm on a spike on something I have to finish today. If this can wait until the weekend, I can sort it out no problem!

**Comment by brendandburns** [comment]
@codefromthecrypt no worries, I actually have time today, I expect I'll get it straightend out. Looks like a dependency issue.

**Comment by codefromthecrypt** [comment]
@brendandburns yep and this will fix (or is at least a workaround to) #3140. I think what's left is to copy plugin configuration that is currently required in our parent pom.xml into the examples whose parents didn't include it (e.g. spotless)

**Review by codefromthecrypt — APPROVED** [review]
LGTM

**Pull request merged**
