### PR TITLE
Add convert v1cronjob to v1job.

### PR DESCRIPTION
**Pull request by 6sco**
This PR will try to implement an acceptable approach for the following proposal https://github.com/kubernetes-client/java/issues/2368

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for sending a PR!

**Comment by brendandburns** [comment]
Looks like you need to run `mvn spotless:apply` to fix formatting.

**Comment by 6sco** [comment]
> Looks like you need to run `mvn spotless:apply` to fix formatting.

Done.

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Comment by brendandburns** [comment]
Turns out I ripped out the v1beta1 code for the 1.25 release anyway (#2385) and converted to V1CronJob

So I think that this is no longer relevant.

**Comment by brendandburns** [comment]
(unless we want to cherry-pick it into older releases)

**Comment by brendandburns** [comment]
Closing this PR since it is no longer relevant. We'd still accept a cherry-pick of this PR into earlier release branches if you want.

**Pull request closed without merging**
