### PR TITLE
Update kubernetes generated code.

### LINKED ISSUE #115: NetworkPolicyPort fails at numerical ports
Any attempt at saving a V1NetworkPolicyPort fails with:
```Invalid value: \"80\": must contain at least one letter or number (a-z, 0-9)```

It looks like this value should be an IntOrString type rather than a string so that the rendered json would be of int type when required and string type otherwise.

### PR DESCRIPTION
**Pull request by brendandburns**
Regenerate code to pick up the `IntOrString` improvements.

Fixes #115 #117 

@mbohlool ptal

@lwander I think this warrants rev.ing a new package.

### CODE REVIEW

**Comment by lwander** [comment]
SGTM, 1.0.0-beta2?

**Comment by brendandburns** [comment]
Works for me...

--brendan

________________________________

**Comment by kadwanev** [comment]
when can a beta2 be pushed to maven?

**Comment by brendandburns** [comment]
I'm working on getting my permissions right to push to Maven...



________________________________________

**Pull request merged**
