### PR TITLE
Update dependencies except for Spring

### PR DESCRIPTION
**Pull request by rjeberhard**
We're seeing OWASP scan reports about okio, which is included by okhttp3. I'm curious about why Dependabot didn't update this dependency? Whatever the answer, here are all of the missing updates except for those from Spring, which seem to require other, compensating changes.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR. I'm wondering if dependabot doesn't do this b/c there are explicit versions in okhttp or somesuch?

Anyway, assuming tests pass:

/lgtm
/approve

**Comment by brendandburns** [comment]
fwiw, dependabot did send one of them:

https://github.com/kubernetes-client/java/pull/2767

**Comment by rjeberhard** [comment]
> fwiw, dependabot did send one of them:
> 
> #2767

Yes, it's good, of course, that Dependabot found this update. That does leave a mystery of why it never offered PR's for the other updates. I looked at the configuration and it's the simple, typical configuration found in many other projects. Because I could see that the okhttp update had not occurred, I ran `mvn versions:display-dependency-updates` and reviewed the output.

**Comment by brendandburns** [comment]
Yeah, it's odd it looks like dependabot has never offered an update for `okhttp` all of the PRs that I can find that reference okhttp are manual:

https://github.com/search?q=repo%3Akubernetes-client%2Fjava+okhttp&type=pullrequests

**Comment by brendandburns** [comment]
@rjeberhard looks like the logback dependency doesn't support Java8?

**Comment by rjeberhard** [comment]
> @rjeberhard looks like the logback dependency doesn't support Java8?

Yeah, I was too hopeful that I'd be able to do all of the updates. I think that the best plan would be to have specific PR's for each dependency similar to what Dependabot should have created.

**Comment by brendandburns** [comment]
Ok, individual targetted PRs makes sense.

I also wonder if we need to move java8 support out into a different fork or some other approach to continuing support for Java8...

**Comment by brendandburns** [comment]
I looked into this more I think logback should move to 1.3.11 not 1.4.11 they claim to be identical except 1.3 supports Java 8...

**Comment by rjeberhard** [comment]
Since this PR is down to just 2 changes, this seems close enough to the goal of having individual PR's. In the future, I'll create individual PR's if Dependabot doesn't generate the necessary updates.

**Pull request merged**
