### PR TITLE
Update openapi metadata from k/k 1.14 branch

### PR DESCRIPTION
**Pull request by yue9944882**
Fixes: #546 

/cc @brendandburns

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks good, but before we merge this, we need to cut a 5.0.0 release.

**Comment by yue9944882** [comment]
@brendandburns there's some break changes in 1.14. we removed `includeUninitialized` and added `fieldManager` (only for patch calls) in the openapi spec, which sadly doesn't preserve backward-compatibility. let me validate the interface changes locally before getting them merged...

**Comment by brendandburns** [comment]
@yue9944882 ping me when this is ready to re-review.

Thanks!

**Comment by yue9944882** [comment]
let's get this in! thanks

**Comment by brendandburns** [comment]
@yue9944882 now that 5.0.0 is merged, please rebase and this is ready to go!

**Comment by yue9944882** [comment]
@brendandburns sry for delaying, i missed your last comment due to the flooding github notification😮 . just rebased and PTAL, thx

**Pull request merged**
