### PR TITLE
Update to the latest sundr generator.

### PR DESCRIPTION
**Pull request by brendandburns**
@yue9944882 please check my changes.

This required some tweaking of imports but I think that maybe they were accidental?

### CODE REVIEW

**Review by yue9944882 — COMMENTED** [review]
LGTM, forcing the format and it's ready to merge

**Comment by brendandburns** [comment]
formatting fixed.

**Comment by brendandburns** [comment]
I think the maven cache is poisoned here. Trying to figure out how to clear it...

**Comment by brendandburns** [comment]
Ok, I cleaned up the maven cache (the only way to do it is to change the cache key!) this is ready to merge.

Thanks

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

is the cache broken due to forcibly terminating the job?

**Pull request merged**
