### PR TITLE
Update to 1.10 API.

### LINKED ISSUE #268: support for kubernetes version 1.9 and 1.10
client supports until 1.8 only, but now there are two server versions ahead of supported versions. 
are there any plans for regenerating client code for these versions.

### PR DESCRIPTION
**Pull request by brendandburns**
Updates to the 1.10 API
Rev to 2.0.0-X since there are some incompatible API changes w/ 1.7/1.8

Fixes #268

### CODE REVIEW

**Comment by brendandburns** [comment]
@kondapally1989

**Comment by kondapally1989** [comment]
@brendandburns 

this looks good to me.

one tiny doubt.
- shouldn't we create  a new branch (maybe 1.8) based on present master branch before merging this.

**Comment by brendandburns** [comment]
The branch already exists:

https://github.com/kubernetes-client/java/tree/client-java-parent-1.0.0

I cut it with the 1.0 release (and there haven't been any bugs since then)

**Comment by brendandburns** [comment]
I'm going to merge this, since I addressed the one comment.  (please let me know if I missed something)

**Pull request merged**
