### PR TITLE
Regenerate for Kubernetes 1.23

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by yue9944882** [comment]
@brendandburns thanks! i think it missed examples for release 14 last time, i will be adding example-14 and 15 together in a follow up.

**Comment by brendandburns** [comment]
@yue9944882 this is mostly ready. I will wait for you to create the new examples directories and then I will rebase this PR, unless you want me to to it in this pr.

**Comment by brendandburns** [comment]
@yue9944882 I went ahead and just fixed up the examples myself.

This should be ready to merge.

**Comment by brendandburns** [comment]
@yue9944882 I fixed the compile error, this is ready to go.

Thanks!

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Comment by yue9944882** [comment]
/hold cancel

b/c the compile failure is fixed

**Pull request merged**
