### PR TITLE
Bump 7.0.0 release

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by yue9944882** [comment]
/hold

holding this before the other opening pulls getting in

**Comment by brendandburns** [comment]
These pom changes will largely get done by the release tooling. I will run a release to 7.0.0 tomorrow sometime, and send the PR.

**Comment by yue9944882** [comment]
can we hold until https://github.com/OpenAPITools/openapi-generator/pull/4475 is released? it's supposed to be out 15th this month i.e. tomorrow. and we can re-generated w/ that release. it will fix https://github.com/kubernetes-client/java/issues/431 and make the test https://github.com/kubernetes-client/java/pull/799 work

**Comment by brendandburns** [comment]
Sure, will wait until next week for that.

**Comment by brendandburns** [comment]
@yue9944882 are we ready to go here?

**Comment by yue9944882** [comment]
/hold cancel

@brendandburns let's proceed!

**Comment by rjeberhard** [comment]
Just curious about the status of the 7.0.0 release.  We're trying to plan our work to stay current with this client.  (Thanks for all of the hard work on this project!)

**Comment by brendandburns** [comment]
I just pushed 7.0.0 to sonatype (should show up in maven central in 1-2 days)

@yue9944882 can you rebase this PR (the maven release process pushes some commits to the repo for the pom files)

Thanks

**Comment by yue9944882** [comment]
rebased and updated changelog given that this release involves many backward-incompatible changes..

**Comment by yue9944882** [comment]
@brendandburns it's been 4 days but i still didnt see it present on the maven central, am i missing anything?

**Pull request merged**
