### PR TITLE
Bump new 5.0.0-beta1 release version

### PR DESCRIPTION
**Pull request by yue9944882**
/cc @brendandburns

### CODE REVIEW

**Comment by brendandburns** [comment]
Don't we need this for the other sub-folder pom.xml files too?

**Comment by brendandburns** [comment]
And do we want to skip straight to a full release instead of a beta? We're going to immediately cut 6.0.0-beta1 anyway to pick up the 1.14 changes...

**Comment by yue9944882** [comment]
> Don't we need this for the other sub-folder pom.xml files too?

do we? the sub-modules are supposed will inherit from parent's version?

> And do we want to skip straight to a full release instead of a beta? We're going to immediately cut 6.0.0-beta1 anyway to pick up the 1.14 changes...

ohh tricked. it's 5.x works for 1.13 and 6.x for 1.14.

**Comment by brendandburns** [comment]
Are the poms set up that way? I feel like the last time I changed this I had to do it everywhere...

**Pull request closed without merging**
