### PR TITLE
Fixed 'remaining' bytes calculation to use the current bufferSize

### LINKED ISSUE #1826: WebSocketStreamHandler.write() : NegativeArraySizeException when calculating 'remaining' byte count
Kubernetes Java Client Version:  13.0.0

In WebSocketStreamHandler.java (line 273), the 'remaining' byte count value is incremented using the cumulative bytesWritten instead of the bufferSize for that iteration causing a java.lang.NegativeArraySizeException.  This issue is likely only seen when copying files larger that 3 times the buffer size (45 MiB).

For testing purposes I changed the min buffer size to 1024 and attempted to copy 4096 bytes.

Initial values:  bytesWritten = 0; remaining = 4096;
Iteration 1:  bytesWritten = 1024; remaining = 3072;  //This is OK.
Iteration 2:  bytesWritten = 2048; remaining = 1024;  //Should be 2048
Iteration 3: bytesWritten = 3072; remaining = -2048; //Should be 1024
Iteration 4: **java.lang.NegativeArraySizeException**

The fix I believe is to decrement remaining by bufferSize:

`        remaining -= bufferSize;`

### PR DESCRIPTION
**Pull request by PredatorVI**
Fixes #1826

### CODE REVIEW

**Comment by PredatorVI** [comment]
CNCF-CLA signed.

**Comment by yue9944882** [comment]
@PredatorVI can you amend your commit with the correct email address? otherwise the CLA check will constantly failing

**Comment by PredatorVI** [comment]
I'm trying but I'm a n00b, sorry.  I amended the commit (I think) from my workstation and pushed it to my fork, but I'm not sure now how to sync that with/to the Pull Request.

**Comment by yue9944882** [comment]
@PredatorVI can you squash your commits into 1 and elaborate the point of the following two commits?

> Removed base64 encoding/decoding from copyFileToPod variants. 
> Removed base64 encoding/decoding from copyFileToPod variants.

**Comment by PredatorVI** [comment]
I don't know how to squash them (n00b again).  I've read some tutorials/blogs and following the steps has not worked.  

There were other changes related to code formatting/whitespace that were introduced due to using my IDE auto-format feature that I didn't notice due to my Git Client configured to ignore whitespace.

As for:

> Removed base64 encoding/decoding from copyFileToPod variants.
> Removed base64 encoding/decoding from copyFileToPod variants.

I don't understand why it shows twice.  The core of the change is based on issue #1822 (https://github.com/kubernetes-client/java/issues/1822#issuecomment-900315846) where it was suggested removing the base64 encoding as it appears to be an extra unneeded step.

Overall, these changes are small and I'm wondering if I should just cancel this and start over.

**Comment by PredatorVI** [comment]
I'm just going to close this and start fresh.  It's stressing me out.

**Pull request closed without merging**
