### PR TITLE
Fixes leader-election unit-test flakiness

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by brendandburns** [comment]
Sadly this isn't the issue. Okhttp is timing out trying to talk to the kubernetes API server.

Have a look at this commit:
https://github.com/kubernetes-client/java/pull/1475/commits/ee135f4bb4269882fbaf79af200f3aa4a889268e

Where I enable some richer logging (and try to disable the timeouts, but that part doesn't seem to be working)

But enabling the richer logging should give you insight into what's going wrong anyway.

**Comment by brendandburns** [comment]
I filled an issue with more details here:
https://github.com/kubernetes-client/java/issues/1480

**Comment by brendandburns** [comment]
I added #1481 to improve logging for these tests.

**Comment by yue9944882** [comment]
@brendandburns the failure will be solved after rebasing onto the latest master branch now

**Pull request merged**
