### PR TITLE
Tidy up SpringBootTests

### PR DESCRIPTION
**Pull request by dsyer**
Tests with [at]SpringBootTest automatically look for configuration files
nested inside them, so you don't need to explicitly enumerate them.

### CODE REVIEW

**Review by yue9944882 — COMMENTED** [review]
/lgtm

can you amend the commit message so the bot can detach the label?

**Comment by dsyer** [comment]
> can you amend the commit message so the bot can detach the label?

I don't think the commit message needed to be amended. Is the bot completely insane?

**Comment by dsyer** [comment]
Yes, the bot is completely insane. Please fix it.

**Comment by yue9944882** [comment]
> Yes, the bot is completely insane. Please fix it.

we're forbidding `@+<Github Users>` in the commit message to avoid spamming references which can be exponentially increasing when users fork the project or even fork the fork..

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
