### PR TITLE
Chore: Docs java highlights

### PR DESCRIPTION
**Pull request by OneCricketeer**
This PR adds syntax highlights to the README

### CODE REVIEW

**Comment by brendandburns** [comment]
this lgtm, if you sign the CLA, I can merge this.

**Comment by OneCricketeer** [comment]
Hi @brendandburns , I am not seeing [anything to sign](https://github.com/kubernetes/community/blob/master/CLA.md#3-complete-signing-process)

**Comment by brendandburns** [comment]
@OneCricketeer please check out https://identity.linuxfoundation.org/projects/cncf

Thanks!

**Pull request merged**
